// Auto-generated from the JMA area master (https://www.jma.go.jp/bosai/common/const/area.json).
// Maps each forecast office code to a lowercased, space-joined string of every
// descendant region/city name, its kana, and its English name, so the weather
// search resolves a place by kanji (函館), kana (はこだて), or English (Hakodate)
// to its office (渡島・檜山地方). Already lowercased; match with a lowercased query.
// Regenerate when the JMA area definitions change.

export const WEATHER_SEARCH_INDEX: Record<string, string> = {
  "100000":
    "群馬県 gunma 南部 southern region 前橋・桐生地域 maebashi kiryu area 前橋市 まえばしし maebashi city 桐生市 きりゅうし kiryu city 渋川市 しぶかわし shibukawa city みどり市 みどりし midori city 榛東村 しんとうむら shinto village 吉岡町 よしおかまち yoshioka town 伊勢崎・太田地域 isesaki ota area 伊勢崎市 いせさきし isesaki city 太田市 おおたし ota city 館林市 たてばやしし tatebayashi city 玉村町 たまむらまち tamamura town 板倉町 いたくらまち itakura town 明和町 めいわまち meiwa town 千代田町 ちよだまち chiyoda town 大泉町 おおいずみまち oizumi town 邑楽町 おうらまち ora town 高崎・藤岡地域 takasaki fujioka area 高崎市 たかさきし takasaki city 藤岡市 ふじおかし fujioka city 富岡市 とみおかし tomioka city 安中市 あんなかし annaka city 上野村 うえのむら ueno village 神流町 かんなまち kanna town 下仁田町 しもにたまち shimonita town 南牧村 なんもくむら nammoku village 甘楽町 かんらまち kanra town 北部 northern region 利根・沼田地域 tone numata area 沼田市 ぬまたし numata city 片品村 かたしなむら katashina village 川場村 かわばむら kawaba village 昭和村 しょうわむら showa village みなかみ町 みなかみまち minakami town 吾妻地域 agatsuma area 中之条町 なかのじょうまち nakanojo town 長野原町 ながのはらまち naganohara town 嬬恋村 つまごいむら tsumagoi village 草津町 くさつまち kusatsu town 高山村 たかやまむら takayama village 東吾妻町 ひがしあがつままち higashiagatsuma town 関東甲信地方 kanto koshin",
  "110000":
    "埼玉県 saitama 南部 southern region 南中部 southern central region さいたま市 さいたまし saitama city 川越市 かわごえし kawagoe city 川口市 かわぐちし kawaguchi city 所沢市 ところざわし tokorozawa city 狭山市 さやまし sayama city 上尾市 あげおし ageo city 蕨市 わらびし warabi city 戸田市 とだし toda city 朝霞市 あさかし asaka city 志木市 しきし shiki city 和光市 わこうし wako city 新座市 にいざし niiza city 桶川市 おけがわし okegawa city 北本市 きたもとし kitamoto city 富士見市 ふじみし fujimi city ふじみ野市 ふじみのし fujimino city 伊奈町 いなまち ina town 三芳町 みよしまち miyoshi town 川島町 かわじままち kawajima town 南東部 south-eastern region 春日部市 かすかべし kasukabe city 草加市 そうかし soka city 越谷市 こしがやし koshigaya city 八潮市 やしおし yashio city 三郷市 みさとし misato city 蓮田市 はすだし hasuda city 幸手市 さってし satte city 吉川市 よしかわし yoshikawa city 白岡市 しらおかし shiraoka city 宮代町 みやしろまち miyashiro town 杉戸町 すぎとまち sugito town 松伏町 まつぶしまち matsubushi town 南西部 south-western region 飯能市 はんのうし hanno city 入間市 いるまし iruma city 坂戸市 さかどし sakado city 鶴ヶ島市 つるがしまし tsurugashima city 日高市 ひだかし hidaka city 毛呂山町 もろやままち moroyama town 越生町 おごせまち ogose town 北部 northern region 北東部 north-eastern region 行田市 ぎょうだし gyoda city 加須市 かぞし kazo city 羽生市 はにゅうし hanyu city 鴻巣市 こうのすし kounosu city 久喜市 くきし kuki city 北西部 north-western region 熊谷市 くまがやし kumagaya city 本庄市 ほんじょうし honjo city 東松山市 ひがしまつやまし higashimatsuyama city 深谷市 ふかやし fukaya city 滑川町 なめがわまち namegawa town 嵐山町 らんざんまち ranzan town 小川町 おがわまち ogawa town 吉見町 よしみまち yoshimi town 鳩山町 はとやままち hatoyama town ときがわ町 ときがわまち tokigawa town 東秩父村 ひがしちちぶむら higashichichibu village 美里町 みさとまち misato town 神川町 かみかわまち kamikawa town 上里町 かみさとまち kamisato town 寄居町 よりいまち yorii town 秩父地方 chichibu district 秩父市 ちちぶし chichibu city 横瀬町 よこぜまち yokoze town 皆野町 みなのまち minano town 長瀞町 ながとろまち nagatoro town 小鹿野町 おがのまち ogano town 関東甲信地方 kanto koshin",
  "120000":
    "千葉県 chiba 北西部 north-western region 千葉中央 central chiba 千葉市 ちばし chiba city 市原市 いちはらし ichihara city 印旛 imba 成田市 なりたし narita city 佐倉市 さくらし sakura city 四街道市 よつかいどうし yotsukaido city 八街市 やちまたし yachimata city 印西市 いんざいし inzai city 白井市 しろいし shiroi city 富里市 とみさとし tomisato city 酒々井町 しすいまち shisui town 栄町 さかえまち sakae town 東葛飾 higashi-katsushika 市川市 いちかわし ichikawa city 船橋市 ふなばしし funabashi city 松戸市 まつどし matsudo city 野田市 のだし noda city 習志野市 ならしのし narashino city 柏市 かしわし kashiwa city 流山市 ながれやまし nagareyama city 八千代市 やちよし yachiyo city 我孫子市 あびこし abiko city 鎌ケ谷市 かまがやし kamagaya city 浦安市 うらやすし urayasu city 北東部 north-eastern region 香取・海匝 katori kaiso 銚子市 ちょうしし choshi city 旭市 あさひし asahi city 匝瑳市 そうさし sosa city 香取市 かとりし katori city 神崎町 こうざきまち kozaki town 多古町 たこまち tako town 東庄町 とうのしょうまち tohnosho town 山武・長生 sammu chosei 茂原市 もばらし mobara city 東金市 とうがねし togane city 山武市 さんむし sammu city 大網白里市 おおあみしらさとし oamishirasato city 九十九里町 くじゅうくりまち kujukuri town 芝山町 しばやままち shibayama town 横芝光町 よこしばひかりまち yokoshibahikari town 一宮町 いちのみやまち ichinomiya town 睦沢町 むつざわまち mutsuzawa town 長生村 ちょうせいむら chosei village 白子町 しらこまち shirako town 長柄町 ながらまち nagara town 長南町 ちょうなんまち chonan town 南部 southern region 君津 kimitsu 木更津市 きさらづし kisarazu city 君津市 きみつし kimitsu city 富津市 ふっつし futtsu city 袖ケ浦市 そでがうらし sodegaura city 夷隅・安房 isumi awa 館山市 たてやまし tateyama city 勝浦市 かつうらし katsuura city 鴨川市 かもがわし kamogawa city 南房総市 みなみぼうそうし minamiboso city いすみ市 いすみし isumi city 大多喜町 おおたきまち otaki town 御宿町 おんじゅくまち onjuku town 鋸南町 きょなんまち kyonan town 関東甲信地方 kanto koshin",
  "130000":
    "東京都 tokyo 東京地方 tokyo region ２３区西部 western region of 23 wards 千代田区 ちよだく chiyoda city 中央区 ちゅうおうく chuo city 港区 みなとく minato city 新宿区 しんじゅくく shinjuku city 文京区 ぶんきょうく bunkyo city 品川区 しながわく shinagawa city 目黒区 めぐろく meguro city 大田区 おおたく ota city 世田谷区 せたがやく setagaya city 渋谷区 しぶやく shibuya city 中野区 なかのく nakano city 杉並区 すぎなみく suginami city 豊島区 としまく toshima city 北区 きたく kita city 板橋区 いたばしく itabashi city 練馬区 ねりまく nerima city ２３区東部 eastern region of 23 wards 台東区 たいとうく taito city 墨田区 すみだく sumida city 江東区 こうとうく koto city 荒川区 あらかわく arakawa city 足立区 あだちく adachi city 葛飾区 かつしかく katsushika city 江戸川区 えどがわく edogawa city 多摩北部 northern tama 立川市 たちかわし tachikawa city 武蔵野市 むさしのし musashino city 三鷹市 みたかし mitaka city 府中市 ふちゅうし fuchu city 昭島市 あきしまし akishima city 調布市 ちょうふし chofu city 小金井市 こがねいし koganei city 小平市 こだいらし kodaira city 東村山市 ひがしむらやまし higashimurayama city 国分寺市 こくぶんじし kokubunji city 国立市 くにたちし kunitachi city 狛江市 こまえし komae city 東大和市 ひがしやまとし higashiyamato city 清瀬市 きよせし kiyose city 東久留米市 ひがしくるめし higashikurume city 武蔵村山市 むさしむらやまし musashimurayama city 西東京市 にしとうきょうし nishitokyo city 多摩西部 western tama 青梅市 おうめし ome city 福生市 ふっさし fussa city 羽村市 はむらし hamura city あきる野市 あきるのし akiruno city 瑞穂町 みずほまち mizuho town 日の出町 ひのでまち hinode town 檜原村 ひのはらむら hinohara village 奥多摩町 おくたままち okutama town 多摩南部 southern tama 八王子市 はちおうじし hachioji city 町田市 まちだし machida city 日野市 ひのし hino city 多摩市 たまし tama city 稲城市 いなぎし inagi city 伊豆諸島北部 northern izu islands 大島 oshima island 大島町 おおしままち oshima town 新島 niijima island 利島村 としまむら toshima village 新島村 にいじまむら niijima village 神津島村 こうづしまむら kouzushima village 伊豆諸島南部 southern izu islands 八丈島 hachijojima island 八丈町 はちじょうまち hachijo town 青ヶ島村 あおがしまむら aogashima village 三宅島 miyakejima island 三宅村 みやけむら miyake village 御蔵島村 みくらじまむら mikurashima village 小笠原諸島 ogasawara islands 小笠原村 おがさわらむら ogasawara village 関東甲信地方 kanto koshin",
  "140000":
    "神奈川県 kanagawa 東部 eastern region 横浜・川崎 yokohama kawasaki 横浜市北部 よこはましほくぶ northern yokohama city 横浜市南部 よこはましなんぶ southern yokohama city 川崎市 かわさきし kawasaki city 湘南 shonan 平塚市 ひらつかし hiratsuka city 藤沢市 ふじさわし fujisawa city 茅ヶ崎市 ちがさきし chigasaki city 大和市 やまとし yamato city 海老名市 えびなし ebina city 座間市 ざまし zama city 綾瀬市 あやせし ayase city 寒川町 さむかわまち samukawa town 大磯町 おおいそまち oiso town 二宮町 にのみやまち ninomiya town 三浦半島 miura peninsula 横須賀市 よこすかし yokosuka city 鎌倉市 かまくらし kamakura city 逗子市 ずしし zushi city 三浦市 みうらし miura city 葉山町 はやままち hayama town 西部 western region 相模原 sagamihara 相模原市西部 さがみはらしせいぶ western sagamihara city 相模原市東部 さがみはらしとうぶ eastern sagamihara city 県央 ken-o 秦野市 はだのし hadano city 厚木市 あつぎし atsugi city 伊勢原市 いせはらし isehara city 愛川町 あいかわまち aikawa town 清川村 きよかわむら kiyokawa village 足柄上 ashigara-kami 南足柄市 みなみあしがらし minamiashigara city 中井町 なかいまち nakai town 大井町 おおいまち oi town 松田町 まつだまち matsuda town 山北町 やまきたまち yamakita town 開成町 かいせいまち kaisei town 西湘 seisho 小田原市 おだわらし odawara city 箱根町 はこねまち hakone town 真鶴町 まなつるまち manazuru town 湯河原町 ゆがわらまち yugawara town 関東甲信地方 kanto koshin",
  "150000":
    "新潟県 niigata 下越 kaetsu 新潟地域 niigata area 新潟市 にいがたし niigata city 燕市 つばめし tsubame city 阿賀野市 あがのし agano city 弥彦村 やひこむら yahiko village 岩船地域 iwafune area 村上市 むらかみし murakami city 関川村 せきかわむら sekikawa village 粟島浦村 あわしまうらむら awashimaura village 新発田地域 shibata area 新発田市 しばたし shibata city 胎内市 たいないし tainai city 聖籠町 せいろうまち seiro town 五泉地域 gosen area 五泉市 ごせんし gosen city 阿賀町 あがまち aga town 中越 chuetsu 長岡地域 nagaoka area 長岡市 ながおかし nagaoka city 小千谷市 おぢやし ojiya city 見附市 みつけし mitsuke city 出雲崎町 いずもざきまち izumozaki town 三条地域 sanjo area 三条市 さんじょうし sanjo city 加茂市 かもし kamo city 田上町 たがみまち tagami town 魚沼市 uonuma city うおぬまし 柏崎地域 kashiwazaki area 柏崎市 かしわざきし kashiwazaki city 刈羽村 かりわむら kariwa village 南魚沼地域 minami-uonuma area 南魚沼市 みなみうおぬまし minamiuonuma city 湯沢町 ゆざわまち yuzawa town 十日町地域 toka-machi area 十日町市 とおかまちし tokamachi city 津南町 つなんまち tsunan town 上越 joetsu 上越市 joetsu city じょうえつし 糸魚川市 itoigawa city いといがわし 妙高市 myoko city みょうこうし 佐渡 sado 佐渡市 さどし sado city 北陸地方 hokuriku",
  "160000":
    "富山県 toyama 東部 eastern region 東部南 south-eastern region 富山市平地 とやましへいち plain area of toyama city 富山市山間部東 とやましさんかんぶひがし eastern mountains region of toyama city 富山市山間部西 とやましさんかんぶにし western mountains region of toyama city 舟橋村 ふなはしむら funahashi village 上市町 かみいちまち kamiichi town 立山町 たてやままち tateyama town 東部北 north-eastern region 魚津市 うおづし uozu city 滑川市 なめりかわし namerikawa city 黒部市 くろべし kurobe city 入善町 にゅうぜんまち nyuzen town 朝日町 あさひまち asahi town 西部 western region 西部北 north-western region 高岡市 たかおかし takaoka city 氷見市 ひみし himi city 小矢部市 おやべし oyabe city 射水市 いみずし imizu city 西部南 south-western region 砺波市 となみし tonami city 南砺市 なんとし nanto city 北陸地方 hokuriku",
  "170000":
    "石川県 ishikawa 加賀 kaga 加賀北部 northern kaga 金沢市 かなざわし kanazawa city かほく市 かほくし kahoku city 津幡町 つばたまち tsubata town 内灘町 うちなだまち uchinada town 加賀南部 southern kaga 小松市 こまつし komatsu city 加賀市 かがし kaga city 白山市 はくさんし hakusan city 能美市 のみし nomi city 野々市市 ののいちし nonoichi city 川北町 かわきたまち kawakita town 能登 noto 能登北部 northern noto 輪島市 わじまし wajima city 珠洲市 すずし suzu city 穴水町 あなみずまち anamizu town 能登町 のとちょう noto town 能登南部 southern noto 七尾市 ななおし nanao city 羽咋市 はくいし hakui city 志賀町 しかまち shika town 宝達志水町 ほうだつしみずちょう hodatsushimizu town 中能登町 なかのとまち nakanoto town 北陸地方 hokuriku",
  "180000":
    "福井県 fukui 嶺北 reihoku 嶺北北部 northern reihoku 福井市 ふくいし fukui city あわら市 あわらし awara city 坂井市 さかいし sakai city 永平寺町 えいへいじちょう eiheiji town 越前町 えちぜんちょう echizen town 嶺北南部 southern reihoku 鯖江市 さばえし sabae city 越前市 えちぜんし echizen city 池田町 いけだちょう ikeda town 南越前町 みなみえちぜんちょう minamiechizen town 奥越 okuetsu 大野市 おおのし ono city 勝山市 かつやまし katsuyama city 嶺南 reinan 嶺南東部 eastern reinan 敦賀市 つるがし tsuruga city 美浜町 みはまちょう mihama town 若狭町 わかさちょう wakasa town 嶺南西部 western reinan 小浜市 おばまし obama city 高浜町 たかはまちょう takahama town おおい町 おおいちょう ohi town 北陸地方 hokuriku",
  "190000":
    "山梨県 yamanashi 中・西部 central western region 中北地域 chuhoku area 甲府市 こうふし kofu city 韮崎市 にらさきし nirasaki city 南アルプス市 みなみあるぷすし minamialps city 北杜市 ほくとし hokuto city 甲斐市 かいし kai city 中央市 ちゅうおうし chuo city 昭和町 しょうわちょう showa town 峡東地域 kyoto area 山梨市 やまなしし yamanashi city 笛吹市 ふえふきし fuefuki city 甲州市 こうしゅうし koshu city 峡南地域 kyonan area 市川三郷町 いちかわみさとちょう ichikawamisato town 早川町 はやかわちょう hayakawa town 身延町 みのぶちょう minobu town 南部町 なんぶちょう nambu town 富士川町 ふじかわちょう fujikawa town 東部・富士五湖 eastern region and fuji five lakes 東部 eastern region 都留市 つるし tsuru city 大月市 おおつきし otsuki city 上野原市 うえのはらし uenohara city 道志村 どうしむら doshi village 小菅村 こすげむら kosuge village 丹波山村 たばやまむら tabayama village 富士五湖 fuji five lakes 富士吉田市 ふじよしだし fujiyoshida city 西桂町 にしかつらちょう nishikatsura town 忍野村 おしのむら oshino village 山中湖村 やまなかこむら yamanakako village 鳴沢村 なるさわむら narusawa village 富士河口湖町 ふじかわぐちこまち fujikawaguchiko town 関東甲信地方 kanto koshin",
  "200000":
    "長野県 nagano 北部 northern region 長野地域 nagano area 長野市長野 ながのしながの nagano, nagano city 長野市鬼無里戸隠 ながのしきなさとがくし kinasatogakushi, nagano city 須坂市 すざかし suzaka city 千曲市 ちくまし chikuma city 坂城町 さかきまち sakaki town 小布施町 おぶせまち obuse town 高山村 たかやまむら takayama village 信濃町 しなのまち shinano town 小川村 おがわむら ogawa village 飯綱町 いいづなまち iizuna town 中野飯山地域 nakano iiyama area 中野市 なかのし nakano city 飯山市 いいやまし iiyama city 山ノ内町 やまのうちまち yamanouchi town 木島平村 きじまだいらむら kijimadaira village 野沢温泉村 のざわおんせんむら nozawaonsen village 栄村 さかえむら sakae village 大北地域 daihoku area 大町市 おおまちし omachi city 池田町 いけだまち ikeda town 松川村 まつかわむら matsukawa village 白馬村 はくばむら hakuba village 小谷村 おたりむら otari village 中部 central region 上田地域 ueda area 上田市 うえだし ueda city 東御市 とうみし tomi city 青木村 あおきむら aoki village 長和町 ながわまち nagawa town 佐久地域 saku area 小諸市 こもろし komoro city 佐久市 さくし saku city 小海町 こうみまち koumi town 川上村 かわかみむら kawakami village 南牧村 みなみまきむら minamimaki village 南相木村 みなみあいきむら minamiaiki village 北相木村 きたあいきむら kitaaiki village 佐久穂町 さくほまち sakuho town 軽井沢町 かるいざわまち karuizawa town 御代田町 みよたまち miyota town 立科町 たてしなまち tateshina town 松本地域 matsumoto area 松本市松本 まつもとしまつもと matsumoto, matsumoto city 塩尻市塩尻 しおじりししおじり shiojiri, shiojiri city 安曇野市 あづみのし azumino city 麻績村 おみむら omi village 生坂村 いくさかむら ikusaka village 山形村 やまがたむら yamagata village 朝日村 あさひむら asahi village 筑北村 ちくほくむら chikuhoku village 乗鞍上高地地域 norikura kamikochi area 松本市乗鞍上高地 まつもとしのりくらかみこうち norikura kamikochi, matsumoto city 諏訪地域 suwa area 岡谷市 おかやし okaya city 諏訪市 すわし suwa city 茅野市 ちのし chino city 下諏訪町 しもすわまち shimosuwa town 富士見町 ふじみまち fujimi town 原村 はらむら hara village 南部 southern region 上伊那地域 kamiina area 伊那市伊那 いなしいな ina, ina city 伊那市長谷 いなしはせ hase, ina city 駒ヶ根市 こまがねし komagane city 辰野町 たつのまち tatsuno town 箕輪町 みのわまち minowa town 飯島町 いいじままち iijima town 南箕輪村 みなみみのわむら minamiminowa village 中川村 なかがわむら nakagawa village 宮田村 みやだむら miyada village 木曽地域 kiso area 塩尻市楢川 しおじりしならかわ narakawa, shiojiri city 上松町 あげまつまち agematsu town 南木曽町 なぎそまち nagiso town 木祖村 きそむら kiso village 王滝村 おうたきむら otaki village 大桑村 おおくわむら okuwa village 木曽町 きそまち kiso town 下伊那地域 shimoina area 飯田市 いいだし iida city 松川町 まつかわまち matsukawa town 高森町 たかもりまち takamori town 阿南町 あなんちょう anan town 阿智村 あちむら achi village 平谷村 ひらやむら hiraya village 根羽村 ねばむら neba village 下條村 しもじょうむら shimojo village 売木村 うるぎむら urugi village 天龍村 てんりゅうむら tenryu village 泰阜村 やすおかむら yasuoka village 喬木村 たかぎむら takagi village 豊丘村 とよおかむら toyooka village 大鹿村 おおしかむら oshika village 関東甲信地方 kanto koshin",
  "210000":
    "岐阜県 gifu 美濃地方 mino region 岐阜・西濃 gifu seino 岐阜市 ぎふし gifu city 大垣市 おおがきし ogaki city 羽島市 はしまし hashima city 各務原市 かかみがはらし kakamigahara city 山県市 やまがたし yamagata city 瑞穂市 みずほし mizuho city 本巣市 もとすし motosu city 海津市 かいづし kaizu city 岐南町 ぎなんちょう ginan town 笠松町 かさまつちょう kasamatsu town 養老町 ようろうちょう yoro town 垂井町 たるいちょう tarui town 関ケ原町 せきがはらちょう sekigahara town 神戸町 ごうどちょう godo town 輪之内町 わのうちちょう wanouchi town 安八町 あんぱちちょう ampachi town 揖斐川町 いびがわちょう ibigawa town 大野町 おおのちょう ono town 池田町 いけだちょう ikeda town 北方町 きたがたちょう kitagata town 東濃 tono 多治見市 たじみし tajimi city 中津川市 なかつがわし nakatsugawa city 瑞浪市 みずなみし mizunami city 恵那市 えなし ena city 土岐市 ときし toki city 中濃 chuno 関市 せきし seki city 美濃市 みのし mino city 美濃加茂市 みのかもし minokamo city 可児市 かにし kani city 郡上市 ぐじょうし gujo city 坂祝町 さかほぎちょう sakahogi town 富加町 とみかちょう tomika town 川辺町 かわべちょう kawabe town 七宗町 ひちそうちょう hichiso town 八百津町 やおつちょう yaotsu town 白川町 しらかわちょう shirakawa town 東白川村 ひがししらかわむら higashishirakawa village 御嵩町 みたけちょう mitake town 飛騨地方 hida region 飛騨北部 northern hida 高山市 たかやまし takayama city 飛騨市 ひだし hida city 白川村 しらかわむら shirakawa village 飛騨南部 southern hida 下呂市 げろし gero city 東海地方 tokai",
  "220000":
    "静岡県 shizuoka 中部 central region 中部南 southern central region 静岡市南部 しずおかしなんぶ southern shizuoka city 島田市 しまだし shimada city 焼津市 やいづし yaizu city 藤枝市 ふじえだし fujieda city 牧之原市 まきのはらし makinohara city 吉田町 よしだちょう yoshida town 中部北 northern central region 静岡市北部 しずおかしほうぶ northern shizuoka city 川根本町 かわねほんちょう kawanehoncho town 伊豆 izu 伊豆北 northern izu 熱海市 あたみし atami city 伊東市 いとうし ito city 伊豆市 いずし izu city 伊豆の国市 いずのくにし izunokuni city 函南町 かんなみちょう kannami town 伊豆南 southern izu 下田市 しもだし shimoda city 東伊豆町 ひがしいずちょう higashiizu town 河津町 かわづちょう kawazu town 南伊豆町 みなみいずちょう miamiizu town 松崎町 まつざきちょう matsuzaki town 西伊豆町 にしいずちょう nishiizu town 東部 eastern region 富士山南東 south-eastern mt. fuji 沼津市 ぬまづし numazu city 三島市 みしまし mishima city 御殿場市 ごてんばし gotemba city 裾野市 すそのし susono city 清水町 しみずちょう shimizu town 長泉町 ながいずみちょう nagaizumi town 小山町 おやまちょう oyama town 富士山南西 south-western mt. fuji 富士宮市 ふじのみやし fujinomiya city 富士市 ふじし fuji city 西部 western region 遠州北 northern enshu 浜松市北部 はままつしほくぶ northern hamamatsu city 遠州南 southern enshu 浜松市南部 はままつしなんぶ southern hamamatsu city 磐田市 いわたし iwata city 掛川市 かけがわし kakegawa city 袋井市 ふくろいし fukuroi city 湖西市 こさいし kosai city 御前崎市 おまえざきし omaezaki city 菊川市 きくがわし kikugawa city 森町 もりまち mori town 東海地方 tokai",
  "230000":
    "愛知県 aichi 西部 western region 尾張東部 eastern owari 名古屋市 なごやし nagoya city 瀬戸市 せとし seto city 春日井市 かすがいし kasugai city 犬山市 いぬやまし inuyama city 小牧市 こまきし komaki city 尾張旭市 おわりあさひし owariasahi city 豊明市 とよあけし toyoake city 日進市 にっしんし nisshin city 長久手市 ながくてし nagakute city 東郷町 とうごうちょう togo town 尾張西部 western owari 一宮市 いちのみやし ichinomiya city 津島市 つしまし tsushima city 江南市 こうなんし konan city 稲沢市 いなざわし inazawa city 岩倉市 いわくらし iwakura city 愛西市 あいさいし aisai city 清須市 きよすし kiyosu city 北名古屋市 きたなごやし kitanagoya city 弥富市 やとみし yatomi city あま市 あまし ama city 豊山町 とよやまちょう toyoyama town 大口町 おおぐちちょう oguchi town 扶桑町 ふそうちょう fuso town 大治町 おおはるちょう oharu town 蟹江町 かにえちょう kanie town 飛島村 とびしまむら tobishima village 知多地域 chita area 半田市 はんだし handa city 常滑市 とこなめし tokoname city 東海市 とうかいし tokai city 大府市 おおぶし obu city 知多市 ちたし chita city 阿久比町 あぐいちょう agui town 東浦町 ひがしうらちょう higashiura town 南知多町 みなみちたちょう minamichita town 美浜町 みはまちょう mihama town 武豊町 たけとよちょう taketoyo town 西三河南部 southern nishi-mikawa region 岡崎市 おかざきし okazaki city 碧南市 へきなんし hekinan city 刈谷市 かりやし kariya city 安城市 あんじょうし anjo city 西尾市 にしおし nishio city 知立市 ちりゅうし chiryu city 高浜市 たかはまし takahama city 幸田町 こうたちょう kota town 西三河北西部 north-western nishi-mikawa region 豊田市西部 とよたしせいぶ western toyota city みよし市 みよしし miyoshi city 東部 eastern region 西三河北東部 north-eastern nishi-mikawa region 豊田市東部 とよたしとうぶ eastern toyota city 東三河北部 northern higashi-mikawa region 新城市 しんしろし shinshiro city 設楽町 したらちょう shitara town 東栄町 とうえいちょう toei town 豊根村 とよねむら toyone village 東三河南部 southern higashi-mikawa region 豊橋市 とよはしし toyohashi city 豊川市 とよかわし toyokawa city 蒲郡市 がまごおりし gamagori city 田原市 たはらし tahara city 東海地方 tokai",
  "240000":
    "三重県 mie 北中部 northern central region 中部 central region 津市東部 つしとうぶ eastern tsu city 津市中西部 つしちゅうせいぶ midwestern tsu city 松阪市東部 まつさかしとうぶ eastern matsusaka city 松阪市西部 まつさかしせいぶ western matsusaka city 多気町 たきちょう taki town 明和町 めいわちょう meiwa town 北部 northern region 四日市市 よっかいちし yokkaichi city 桑名市 くわなし kuwana city 鈴鹿市 すずかし suzuka city 亀山市 かめやまし kameyama city いなべ市 いなべし inabe city 木曽岬町 きそさきちょう kisosaki town 東員町 とういんちょう toin town 菰野町 こものちょう komono town 朝日町 あさひちょう asahi town 川越町 かわごえちょう kawagoe town 伊賀 iga 名張市 なばりし nabari city 伊賀市 いがし iga city 南部 southern region 伊勢志摩 ise shima 伊勢市 いせし ise city 鳥羽市 とばし toba city 志摩市 しまし shima city 玉城町 たまきちょう tamaki town 度会町 わたらいちょう watarai town 南伊勢町 みなみいせちょう minamiise town 紀勢・東紀州 kisei higashi-kishu 尾鷲市 おわせし owase city 熊野市 くまのし kumano city 大台町 おおだいちょう odai town 大紀町 たいきちょう taiki town 紀北町 きほくちょう kihoku town 御浜町 みはまちょう mihama town 紀宝町 きほうちょう kiho town 東海地方 tokai",
  "250000":
    "滋賀県 shiga 南部 southern region 近江南部 southern omi region 大津市南部 おおつしなんぶ southern otsu city 草津市 くさつし kusatsu city 守山市 もりやまし moriyama city 栗東市 りっとうし ritto city 野洲市 やすし yasu city 東近江 higashi-omi 近江八幡市 おうみはちまんし omihachiman city 東近江市 ひがしおうみし higashiomi city 日野町 ひのちょう hino town 竜王町 りゅうおうちょう ryuoh town 甲賀 koka 甲賀市 こうかし koka city 湖南市 こなんし konan city 北部 northern region 近江西部 western omi 大津市北部 おおつしほくぶ northern otsu city 高島市 たかしまし takashima city 湖北 kohoku 長浜市 ながはまし nagahama city 米原市 まいばらし maibara city 湖東 koto 彦根市 ひこねし hikone city 愛荘町 あいしょうちょう aisho town 豊郷町 とよさとちょう toyosato town 甲良町 こうらちょう kora town 多賀町 たがちょう taga town 近畿地方 kinki",
  "260000":
    "京都府 kyoto 南部 southern region 京都・亀岡 kyoto kameoka 京都市 きょうとし kyoto city 亀岡市 かめおかし kameoka city 向日市 むこうし muko city 長岡京市 ながおかきょうし nagaokakyo city 大山崎町 おおやまざきちょう oyamazaki town 南丹・京丹波 nantan kyotamba 南丹市 なんたんし nantan city 京丹波町 きょうたんばちょう kyotamba town 山城中部 central yamashiro 宇治市 うじし uji city 城陽市 じょうようし joyo city 八幡市 やわたし yawata city 京田辺市 きょうたなべし kyotanabe city 久御山町 くみやまちょう kumiyama town 井手町 いでちょう ide town 宇治田原町 うじたわらちょう ujitawara town 山城南部 southern yamashiro 木津川市 きづがわし kizugawa city 笠置町 かさぎちょう kasagi town 和束町 わづかちょう wazuka town 精華町 せいかちょう seika town 南山城村 みなみやましろむら minamiyamashiro village 北部 northern region 丹後 tango 宮津市 みやづし miyazu city 京丹後市 きょうたんごし kyotango city 伊根町 いねちょう ine town 与謝野町 よさのちょう yosano town 舞鶴・綾部 maizuru ayabe 舞鶴市 まいづるし maizuru city 綾部市 あやべし ayabe city 福知山 fukuchiyama 福知山市 ふくちやまし fukuchiyama city 近畿地方 kinki",
  "270000":
    "大阪府 osaka prefecture 大阪市 osaka city おおさかし 北大阪 kita-osaka 豊中市 とよなかし toyonaka city 池田市 いけだし ikeda city 吹田市 すいたし suita city 高槻市 たかつきし takatsuki city 茨木市 いばらきし ibaraki city 箕面市 みのおし minoh city 摂津市 せっつし settsu city 島本町 しまもとちょう shimamoto town 豊能町 とよのちょう toyono town 能勢町 のせちょう nose town 東部大阪 eastern osaka 守口市 もりぐちし moriguchi city 枚方市 ひらかたし hirakata city 八尾市 やおし yao city 寝屋川市 ねやがわし neyagawa city 大東市 だいとうし daito city 柏原市 かしわらし kashiwara city 門真市 かどまし kadoma city 東大阪市 ひがしおおさかし higashiosaka city 四條畷市 しじょうなわてし shijonawate city 交野市 かたのし katano city 南河内 minami-kawachi 富田林市 とんだばやしし tondabayashi city 河内長野市 かわちながのし kawachinagano city 松原市 まつばらし matsubara city 羽曳野市 はびきのし habikino city 藤井寺市 ふじいでらし fujiidera city 大阪狭山市 おおさかさやまし osakasayama city 太子町 たいしちょう taishi town 河南町 かなんちょう kanan town 千早赤阪村 ちはやあかさかむら chihayaakasaka village 泉州 senshu 堺市 さかいし sakai city 岸和田市 きしわだし kishiwada city 泉大津市 いずみおおつし izumiotsu city 貝塚市 かいづかし kaizuka city 泉佐野市 いずみさのし izumisano city 和泉市 いずみし izumi city 高石市 たかいしし takaishi city 泉南市 せんなんし sennan city 阪南市 はんなんし hannan city 忠岡町 ただおかちょう tadaoka town 熊取町 くまとりちょう kumatori town 田尻町 たじりちょう tajiri town 岬町 みさきちょう misaki town 近畿地方 kinki",
  "280000":
    "兵庫県 hyogo 南部 southern region 阪神 hanshin 神戸市東灘区 こうべしひがしなだく kobe city higashinada ward 神戸市灘区 こうべしなだく kobe city nada ward 神戸市兵庫区 こうべしひょうごく kobe city hyogo ward 神戸市長田区 こうべしながたく kobe city nagata ward 神戸市須磨区 こうべしすまく kobe city suma ward 神戸市垂水区 こうべしたるみく kobe city tarumi ward 神戸市北区 こうべしきたく kobe city kita ward 神戸市中央区 こうべしちゅうおうく kobe city chuo ward 神戸市西区 こうべしにしく kobe city nishi ward 尼崎市 あまがさきし amagasaki city 西宮市 にしのみやし nishinomiya city 芦屋市 あしやし ashiya city 伊丹市 いたみし itami city 宝塚市 たからづかし takarazuka city 川西市 かわにしし kawanishi city 三田市 さんだし sanda city 猪名川町 いながわちょう inagawa town 北播丹波 hokuban tamba 西脇市 にしわきし nishiwaki city 丹波篠山市 たんばささやまし tanba sasayama city 丹波市 たんばし tamba city 多可町 たかちょう taka town 播磨北西部 north-western harima 宍粟市 しそうし shiso city 市川町 いちかわちょう ichikawa town 福崎町 ふくさきちょう fukusaki town 神河町 かみかわちょう kamikawa town 佐用町 さようちょう sayo town 播磨南東部 south-eastern harima 明石市 あかしし akashi city 加古川市 かこがわし kakogawa city 三木市 みきし miki city 高砂市 たかさごし takasago city 小野市 おのし ono city 加西市 かさいし kasai city 加東市 かとうし kato city 稲美町 いなみちょう inami town 播磨町 はりまちょう harima town 播磨南西部 south-western harima 姫路市 ひめじし himeji city 相生市 あいおいし aioi city 赤穂市 あこうし ako city たつの市 たつのし tatsuno city 太子町 たいしちょう taishi town 上郡町 かみごおりちょう kamigori town 淡路島 awajishima 洲本市 すもとし sumoto city 南あわじ市 みなみあわじし minamiawaji city 淡路市 あわじし awaji city 北部 northern region 但馬北部 northern tajima 豊岡市 とよおかし toyooka city 香美町 かみちょう kami town 新温泉町 しんおんせんちょう shinonsen town 但馬南部 southern tajima 養父市 やぶし yabu city 朝来市 あさごし asago city 近畿地方 kinki",
  "290000":
    "奈良県 nara 北部 northern region 北西部 north-western region 奈良市西部 ならしせいぶ western nara city 奈良市東部 ならしとうぶ eastern nara city 大和高田市 やまとたかだし yamatotakada city 大和郡山市 やまとこおりやまし yamatokoriyama city 天理市 てんりし tenri city 橿原市 かしはらし kashihara city 桜井市 さくらいし sakurai city 御所市 ごせし gose city 生駒市 いこまし ikoma city 香芝市 かしばし kashiba city 葛城市 かつらぎし katsuragi city 平群町 へぐりちょう heguri town 三郷町 さんごうちょう sango town 斑鳩町 いかるがちょう ikaruga town 安堵町 あんどちょう ando town 川西町 かわにしちょう kawanishi town 三宅町 みやけちょう miyake town 田原本町 たわらもとちょう tawaramoto town 高取町 たかとりちょう takatori town 明日香村 あすかむら asuka village 上牧町 かんまきちょう kammaki town 王寺町 おうじちょう oji town 広陵町 こうりょうちょう koryo town 河合町 かわいちょう kawai town 北東部 north-eastern region 宇陀市 うだし uda city 山添村 やまぞえむら yamazoe village 五條・北部吉野 gojo and northern yoshino 五條市北部 ごじょうしほくぶ northern gojo city 吉野町 よしのちょう yoshino town 大淀町 おおよどちょう oyodo town 下市町 しもいちちょう shimoichi town 南部 southern region 南東部 south-eastern region 曽爾村 そにむら soni village 御杖村 みつえむら mitsue village 黒滝村 くろたきむら kurotaki village 天川村 てんかわむら tenkawa village 下北山村 しもきたやまむら shimokitayama village 上北山村 かみきたやまむら kamikitayama village 川上村 かわかみむら kawakami village 東吉野村 ひがしよしのむら higashiyoshino village 南西部 south-western region 五條市南部 ごじょうしなんぶ southern gojo city 野迫川村 のせがわむら nosegawa village 十津川村 とつかわむら totsukawa village 近畿地方 kinki",
  "300000":
    "和歌山県 wakayama 北部 northern region 紀北 kihoku 和歌山市 わかやまし wakayama city 海南市 かいなんし kainan city 橋本市 はしもとし hashimoto city 紀の川市 きのかわし kinokawa city 岩出市 いわでし iwade city 紀美野町 きみのちょう kimino town かつらぎ町かつらぎ かつらぎちょうかつらぎ katsuragi, katsuragi town かつらぎ町花園 かつらぎちょうはなぞの hanazono, katsuragi town 九度山町 くどやまちょう kudoyama town 高野町 こうやちょう koya town 紀中 kichu 有田市 ありだし arida city 御坊市 ごぼうし gobo city 湯浅町 ゆあさちょう yuasa town 広川町 ひろがわちょう hirogawa town 有田川町吉備金屋 ありだがわちょうきびかなや kibikanaya, aridagawa town 有田川町清水 ありだがわちょうしみず shimizu, aridagawa town 美浜町 みはまちょう mihama town 日高町 ひだかちょう hidaka town 由良町 ゆらちょう yura town 印南町 いなみちょう inami town みなべ町 みなべちょう minabe town 日高川町川辺 ひだかがわちょうかわべ kawabe, hidakagawa town 日高川町中津 ひだかがわちょうなかつ nakatsu, hidakagawa town 日高川町美山 ひだかがわちょうみやま miyama, hidakagawa town 南部 southern region 田辺・西牟婁 tanabe nishimuro 田辺市田辺 たなべしたなべ tanabe, tanabe city 田辺市龍神 たなべしりゅうじん ryujin, tanabe city 田辺市中辺路 たなべしなかへち nakahechi, tanabe city 田辺市大塔 たなべしおおとう oto, tanabe city 田辺市本宮 たなべしほんぐう hongu, tanabe city 白浜町 しらはまちょう shirahama town 上富田町 かみとんだちょう kamitonda town すさみ町 すさみちょう susami town 新宮・東牟婁 shingu higashimuro 新宮市 しんぐうし shingu city 那智勝浦町 なちかつうらちょう nachikatsuura town 太地町 たいじちょう taiji town 古座川町 こざがわちょう kozagawa town 北山村 きたやまむら kitayama village 串本町 くしもとちょう kushimoto town 近畿地方 kinki",
  "310000":
    "鳥取県 tottori 東部 eastern region 鳥取地区 tottori district 鳥取市北部 とっとりしほくぶ northern tottori city 岩美町 いわみちょう iwami town 八頭地区 yazu district 鳥取市南部 とっとりしなんぶ southern tottori city 若桜町 わかさちょう wakasa town 智頭町 ちづちょう chizu town 八頭町 やずちょう yazu town 中・西部 central western region 倉吉地区 kurayoshi district 倉吉市 くらよしし kurayoshi city 三朝町 みささちょう misasa town 湯梨浜町 ゆりはまちょう yurihama town 琴浦町 ことうらちょう kotoura town 北栄町 ほくえいちょう hokuei town 米子地区 yonago district 米子市 よなごし yonago city 境港市 さかいみなとし sakaiminato city 日吉津村 ひえづそん hiezu village 大山町 だいせんちょう daisen town 南部町 なんぶちょう nambu town 伯耆町 ほうきちょう hoki town 日野地区 hino district 日南町 にちなんちょう nichinan town 日野町 ひのちょう hino town 江府町 こうふちょう kofu town 中国地方（山口県を除く） chugoku (excluding yamaguchi)",
  "320000":
    "島根県 shimane 東部 eastern region 松江地区 matsue district 松江市 まつえし matsue city 安来市 やすぎし yasugi city 出雲地区 izumo district 出雲市 いずもし izumo city 雲南地区 unnan district 雲南市 うんなんし unnan city 奥出雲町 おくいずもちょう okuizumo town 飯南町 いいなんちょう iinan town 西部 western region 大田邑智地区 oda ochi district 大田市 おおだし ohda city 川本町 かわもとまち kawamoto town 美郷町 みさとちょう misato town 邑南町 おおなんちょう onan town 浜田地区 hamada district 浜田市 はまだし hamada city 江津市 ごうつし gotsu city 益田地区 masuda district 益田市 ますだし masuda city 津和野町 つわのちょう tsuwano town 吉賀町 よしかちょう yoshika town 隠岐 oki 海士町 あまちょう ama town 西ノ島町 にしのしまちょう nishinoshima town 知夫村 ちぶむら chibu village 隠岐の島町 おきのしまちょう okinoshima town 中国地方（山口県を除く） chugoku (excluding yamaguchi)",
  "330000":
    "岡山県 okayama 南部 southern region 岡山地域 okayama area 岡山市 おかやまし okayama city 玉野市 たまのし tamano city 瀬戸内市 せとうちし setouchi city 吉備中央町 きびちゅうおうちょう kibichuo town 東備地域 tobi area 備前市 びぜんし bizen city 赤磐市 あかいわし akaiwa city 和気町 わけちょう wake town 倉敷地域 kurashiki area 倉敷市 くらしきし kurashiki city 総社市 そうじゃし soja city 早島町 はやしまちょう hayashima town 井笠地域 ikasa area 笠岡市 かさおかし kasaoka city 井原市 いばらし ibara city 浅口市 あさくちし asakuchi city 里庄町 さとしょうちょう satosho town 矢掛町 やかげちょう yakage town 高梁地域 takahashi area 高梁市 たかはしし takahashi city 北部 northern region 新見地域 niimi area 新見市 にいみし niimi city 真庭地域 maniwa area 真庭市 まにわし maniwa city 新庄村 しんじょうそん shinjo village 津山地域 tsuyama area 津山市 つやまし tsuyama city 鏡野町 かがみのちょう kagamino town 久米南町 くめなんちょう kumenan town 美咲町 みさきちょう misaki town 勝英地域 shoei area 美作市 みまさかし mimasaka city 勝央町 しょうおうちょう shoo town 奈義町 なぎちょう nagi town 西粟倉村 にしあわくらそん nishiawakura village 中国地方（山口県を除く） chugoku (excluding yamaguchi)",
  "340000":
    "広島県 hiroshima 南部 southern region 広島・呉 hiroshima kure 広島市中区 ひろしましなかく hiroshima city naka ward 広島市東区 ひろしましひがしく hiroshima city higashi ward 広島市南区 ひろしましみなみく hiroshima city minami ward 広島市西区 ひろしましにしく hiroshima city nishi ward 広島市安佐南区 ひろしましあさみなみく hiroshima city asaminami ward 広島市安佐北区 ひろしましあさきたく hiroshima city asakita ward 広島市安芸区 ひろしましあきく hiroshima city aki ward 広島市佐伯区 ひろしましさえきく hiroshima city saeki ward 呉市 くれし kure city 大竹市 おおたけし otake city 廿日市市 はつかいちし hatsukaichi city 江田島市 えたじまし etajima city 府中町 ふちゅうちょう fuchu town 海田町 かいたちょう kaita town 熊野町 くまのちょう kumano town 坂町 さかちょう saka town 福山・尾三 fukuyama bisan 三原市 みはらし mihara city 尾道市 おのみちし onomichi city 福山市 ふくやまし fukuyama city 府中市 ふちゅうし fuchu city 世羅町 せらちょう sera town 神石高原町 じんせきこうげんちょう jinsekikogen town 東広島・竹原 higashi-hiroshima takehara 竹原市 たけはらし takehara city 東広島市 ひがしひろしまし higashihiroshima city 大崎上島町 おおさきかみじまちょう osakikamijima town 北部 northern region 備北 bihoku 三次市 みよしし miyoshi city 庄原市 しょうばらし shobara city 芸北 geihoku 安芸高田市 あきたかたし akitakata city 安芸太田町 あきおおたちょう akiota town 北広島町 きたひろしまちょう kitahiroshima town 中国地方（山口県を除く） chugoku (excluding yamaguchi)",
  "350000":
    "山口県 yamaguchi 西部 western region 下関 shimonoseki 下関市 しものせきし shimonoseki city 宇部・山陽小野田 ube and sanyo onoda 宇部市 うべし ube city 山陽小野田市 さんようおのだし sanyo onoda city 中部 central region 山口・防府 yamaguchi hofu 山口市 やまぐちし yamaguchi city 防府市 ほうふし hofu city 周南・下松 shunan kudamatsu 下松市 くだまつし kudamatsu city 周南市 しゅうなんし shunan city 東部 eastern region 岩国 iwakuni 岩国市 いわくにし iwakuni city 和木町 わきちょう waki town 柳井・光 yanai hikari 光市 ひかりし hikari city 柳井市 やないし yanai city 周防大島町 すおうおおしまちょう suo oshima town 上関町 かみのせきちょう kaminoseki town 田布施町 たぶせちょう tabuse town 平生町 ひらおちょう hirao town 北部 northern region 萩・美祢 hagi mine 萩市 はぎし hagi city 美祢市 みねし mine city 阿武町 あぶちょう abu town 長門 nagato 長門市 ながとし nagato city 九州北部地方（山口県を含む） northern kyushu (including yamaguchi)",
  "360000":
    "徳島県 tokushima 北部 northern region 徳島・鳴門 tokushima naruto 徳島市 とくしまし tokushima city 鳴門市 なるとし naruto city 小松島市 こまつしまし komatsushima city 松茂町 まつしげちょう matsushige town 北島町 きたじまちょう kitajima town 藍住町 あいずみちょう aizumi town 板野町 いたのちょう itano town 美馬北部・阿北 northern mima and ahoku 吉野川市 よしのがわし yoshinogawa city 阿波市 あわし awa city 美馬市脇・美馬・穴吹 みましわき・みま・あなぶき waki mima anabuki, mima city 石井町 いしいちょう ishii town 上板町 かみいたちょう kamiita town つるぎ町半田・貞光 つるぎちょうはんだ・さだみつ handa sadamitsu, tsurugi town 美馬南部・神山 southern mima and kamiyama 美馬市木屋平 みましこやだいら koyadaira, mima city 佐那河内村 さなごうちそん sanagochi village 神山町 かみやまちょう kamiyama town つるぎ町一宇 つるぎちょういちう ichiu, tsurugi town 三好 miyoshi 三好市 みよしし miyoshi city 東みよし町 ひがしみよしちょう higashimiyoshi town 南部 southern region 阿南 anan 阿南市 あなんし anan city 那賀・勝浦 naka katsuura 勝浦町 かつうらちょう katsuura town 上勝町 かみかつちょう kamikatsu town 那賀町 なかちょう naka town 海部 kaifu 牟岐町 むぎちょう mugi town 美波町 みなみちょう minami town 海陽町 かいようちょう kaiyo town 四国地方 shikoku",
  "370000":
    "香川県 kagawa prefecture 高松地域 takamatsu area 高松市 たかまつし takamatsu city 直島町 なおしまちょう naoshima town 小豆 shozu 土庄町 とのしょうちょう tonosho town 小豆島町 しょうどしまちょう shodoshima town 東讃 tosan さぬき市 さぬきし sanuki city 東かがわ市 ひがしかがわし higashikagawa city 三木町 みきちょう miki town 中讃 chusan 丸亀市 まるがめし marugame city 坂出市 さかいでし sakaide city 善通寺市 ぜんつうじし zentsuji city 宇多津町 うたづちょう utazu town 綾川町 あやがわちょう ayagawa town 琴平町 ことひらちょう kotohira town 多度津町 たどつちょう tadotsu town まんのう町 まんのうちょう manno town 西讃 seisan 観音寺市 かんおんじし kanonji city 三豊市 みとよし mitoyo city 四国地方 shikoku",
  "380000":
    "愛媛県 ehime 中予 chuyo 松山市 まつやまし matsuyama city 伊予市 いよし iyo city 東温市 とうおんし toon city 久万高原町 くまこうげんちょう kumakogen town 松前町 まさきちょう masaki town 砥部町 とべちょう tobe town 東予 toyo 東予東部 eastern toyo 新居浜市 にいはまし niihama city 西条市 さいじょうし saijo city 四国中央市 しこくちゅうおうし shikokuchuo city 東予西部 western toyo 今治市 いまばりし imabari city 上島町 かみじまちょう kamijima town 南予 nan-yo 南予北部 northern nan-yo 八幡浜市 やわたはまし yawatahama city 大洲市 おおずし ozu city 西予市 せいよし seiyo city 内子町 うちこちょう uchiko town 伊方町 いかたちょう ikata town 南予南部 southern nan-yo 宇和島市 うわじまし uwajima city 松野町 まつのちょう matsuno town 鬼北町 きほくちょう kihoku town 愛南町 あいなんちょう ainan town 四国地方 shikoku",
  "390000":
    "高知県 kochi 中部 central region 高知中央 central kochi 高知市 こうちし kochi city 南国市 なんこくし nankoku city 土佐市 とさし tosa city 須崎市 すさきし susaki city 香南市 こうなんし konan city 香美市 かみし kami city いの町 いのちょう ino town 日高村 ひだかむら hidaka village 嶺北 reihoku 本山町 もとやまちょう motoyama town 大豊町 おおとよちょう otoyo town 土佐町 とさちょう tosa town 大川村 おおかわむら okawa village 高吾北 kogohoku 仁淀川町 によどがわちょう niyodogawa town 佐川町 さかわちょう sakawa town 越知町 おちちょう ochi town 東部 eastern region 室戸 muroto 室戸市 むろとし muroto city 東洋町 とうようちょう toyo town 安芸 aki 安芸市 あきし aki city 奈半利町 なはりちょう nahari town 田野町 たのちょう tano town 安田町 やすだちょう yasuda town 北川村 きたがわむら kitagawa village 馬路村 うまじむら umaji village 芸西村 げいせいむら geisei village 西部 western region 幡多 hata 宿毛市 すくもし sukumo city 土佐清水市 とさしみずし tosashimizu city 四万十市 しまんとし shimanto city 大月町 おおつきちょう otsuki town 三原村 みはらむら mihara village 黒潮町 くろしおちょう kuroshio town 高幡 koban 中土佐町 なかとさちょう nakatosa town 檮原町 ゆすはらちょう yusuhara town 津野町 つのちょう tsuno town 四万十町 しまんとちょう shimanto town 四国地方 shikoku",
  "400000":
    "福岡県 fukuoka 福岡地方 fukuoka region 福岡市 ふくおかし fukuoka city 筑紫野市 ちくしのし chikushino city 春日市 かすがし kasuga city 大野城市 おおのじょうし onojo city 宗像市 むなかたし munakata city 太宰府市 だざいふし dazaifu city 古賀市 こがし koga city 福津市 ふくつし fukutsu city 糸島市 いとしまし itoshima city 那珂川市 なかがわし nakagawa city 宇美町 うみまち umi town 篠栗町 ささぐりまち sasaguri town 志免町 しめまち shime town 須恵町 すえまち sue town 新宮町 しんぐうまち shingu town 久山町 ひさやままち hisayama town 粕屋町 かすやまち kasuya town 北九州地方 kitakyushu region 北九州・遠賀地区 kitakyushu onga district 北九州市 きたきゅうしゅうし kitakyushu city 中間市 なかまし nakama city 芦屋町 あしやまち ashiya town 水巻町 みずまきまち mizumaki town 岡垣町 おかがきまち okagaki town 遠賀町 おんがちょう onga town 京築 keichiku 行橋市 ゆくはしし yukuhashi city 豊前市 ぶぜんし buzen city 苅田町 かんだまち kanda town みやこ町 みやこまち miyako town 吉富町 よしとみまち yoshitomi town 上毛町 こうげまち koge town 築上町 ちくじょうまち chikujo town 筑豊地方 chikuho region 直方市 のおがたし nogata city 飯塚市 いいづかし iizuka city 田川市 たがわし tagawa city 宮若市 みやわかし miyawaka city 嘉麻市 かまし kama city 小竹町 こたけまち kotake town 鞍手町 くらてまち kurate town 桂川町 けいせんまち keisen town 香春町 かわらまち kawara town 添田町 そえだまち soeda town 糸田町 いとだまち itoda town 川崎町 かわさきまち kawasaki town 大任町 おおとうまち oto town 赤村 あかむら aka village 福智町 ふくちまち fukuchi town 筑後地方 chikugo region 筑後北部 northern chikugo 久留米市 くるめし kurume city 小郡市 おごおりし ogori city うきは市 うきはし ukiha city 朝倉市 あさくらし asakura city 筑前町 ちくぜんまち chikuzen town 東峰村 とうほうむら toho village 大刀洗町 たちあらいまち tachiarai town 筑後南部 southern chikugo 大牟田市 おおむたし omuta city 柳川市 やながわし yanagawa city 八女市 やめし yame city 筑後市 ちくごし chikugo city 大川市 おおかわし okawa city みやま市 みやまし miyama city 大木町 おおきまち oki town 広川町 ひろかわまち hirokawa town 九州北部地方（山口県を含む） northern kyushu (including yamaguchi)",
  "410000":
    "佐賀県 saga 南部 southern region 佐賀多久地区 saga taku district 佐賀市 さがし saga city 多久市 たくし taku city 小城市 おぎし ogi city 鳥栖地区 tosu district 鳥栖市 とすし tosu city 神埼市 かんざきし kanzaki city 吉野ヶ里町 よしのがりちょう yoshinogari town 基山町 きやまちょう kiyama town 上峰町 かみみねちょう kamimine town みやき町 みやきちょう miyaki town 武雄地区 takeo district 武雄市 たけおし takeo city 大町町 おおまちちょう omachi town 江北町 こうほくまち kohoku town 白石町 しろいしちょう shiroishi town 鹿島地区 kashima district 鹿島市 かしまし kashima city 嬉野市 うれしのし ureshino city 太良町 たらちょう tara town 北部 northern region 唐津地区 karatsu district 唐津市 からつし karatsu city 玄海町 げんかいちょう genkai town 伊万里地区 imari district 伊万里市 いまりし imari city 有田町 ありたちょう arita town 九州北部地方（山口県を含む） northern kyushu (including yamaguchi)",
  "420000":
    "長崎県 nagasaki 南部 southern region 島原半島 shimabara peninsula 島原市 しまばらし shimabara city 雲仙市 うんぜんし unzen city 南島原市 みなみしまばらし minamishimabara city 長崎地区 nagasaki district 長崎市 ながさきし nagasaki city 長与町 ながよちょう nagayo town 時津町 とぎつちょう togitsu town 諫早・大村地区 isahaya omura district 諫早市 いさはやし isahaya city 大村市 おおむらし omura city 西彼杵半島 nishisonogi peninsula 西海市（江島・平島を除く） さいかいし saikai city (excluding enoshima and tairashima) 北部 northern region 平戸・松浦地区 hirado matsuura district 平戸市 ひらどし hirado city 松浦市 まつうらし matsuura city 佐世保・東彼地区 sasebo tohi district 佐世保市（宇久地域を除く） させぼし sasebo city (excluding uku area) 東彼杵町 ひがしそのぎちょう higashisonogi town 川棚町 かわたなちょう kawatana town 波佐見町 はさみちょう hasami town 佐々町 さざちょう saza town 壱岐・対馬 iki tsushima 壱岐 iki 壱岐市 いきし iki city 上対馬 kamitsushima 対馬市上対馬 つしましかみつしま kamitsushima, tsushima city 下対馬 shimotsushima 対馬市下対馬 つしまししもつしま shimotsushima, tsushima city 五島 goto 上五島 kamigoto 佐世保市（宇久地域） sasebo city (uku area) 西海市（江島・平島） saikai city (enoshima and tairashima) 小値賀町 おぢかちょう ojika town 新上五島町 しんかみごとうちょう shinkamigoto town 下五島 shimogoto 五島市 ごとうし goto city 九州北部地方（山口県を含む） northern kyushu (including yamaguchi)",
  "430000":
    "熊本県 kumamoto 熊本地方 kumamoto region 熊本市 kumamoto city くまもとし 山鹿菊池 yamaga kikuchi 山鹿市 やまがし yamaga city 菊池市 きくちし kikuchi city 合志市 こうしし koshi city 大津町 おおづまち ozu town 菊陽町 きくようまち kikuyo town 荒尾玉名 arao tamana 荒尾市 あらおし arao city 玉名市 たまなし tamana city 玉東町 ぎょくとうまち gyokuto town 南関町 なんかんまち nankan town 長洲町 ながすまち nagasu town 和水町 なごみまち nagomi town 上益城 kamimashiki 西原村 にしはらむら nishihara village 御船町 みふねまち mifune town 嘉島町 かしままち kashima town 益城町 ましきまち mashiki town 甲佐町 こうさまち kosa town 山都町 やまとちょう yamato town 宇城八代 uki yatsushiro 八代市西部 やつしろしせいぶ western yatsushiro city 八代市東部 やつしろしとうぶ eastern yatsushiro city 宇土市 うとし uto city 宇城市 うきし uki city 美里町 みさとまち misato town 氷川町 ひかわちょう hikawa town 阿蘇地方 aso region 阿蘇市 あそし aso city 南小国町 みなみおぐにまち minamioguni town 小国町 おぐにまち oguni town 産山村 うぶやまむら ubuyama village 高森町 たかもりまち takamori town 南阿蘇村 みなみあそむら minamiaso village 天草・芦北地方 amakusa ashikita region 天草地方 amakusa region 上天草市 かみあまくさし kamiamakusa city 天草市 あまくさし amakusa city 苓北町 れいほくまち reihoku town 芦北地方 ashikita region 水俣市 みなまたし minamata city 芦北町 あしきたまち ashikita town 津奈木町 つなぎまち tsunagi town 球磨地方 kuma region 人吉市 ひとよしし hitoyoshi city 錦町 にしきまち nishiki town 多良木町 たらぎまち taragi town 湯前町 ゆのまえまち yunomae town 水上村 みずかみむら mizukami village 相良村 さがらむら sagara village 五木村 いつきむら itsuki village 山江村 やまえむら yamae village 球磨村 くまむら kuma village あさぎり町 あさぎりちょう asagiri town 九州北部地方（山口県を含む） northern kyushu (including yamaguchi)",
  "440000":
    "大分県 oita 中部 central region 大分市 おおいたし oita city 別府市 べっぷし beppu city 臼杵市 うすきし usuki city 津久見市 つくみし tsukumi city 杵築市 きつきし kitsuki city 由布市 ゆふし yufu city 日出町 ひじまち hiji town 北部 northern region 中津市 なかつし nakatsu city 豊後高田市 ぶんごたかだし bungotakada city 宇佐市 うさし usa city 国東市 くにさきし kunisaki city 姫島村 ひめしまむら himeshima village 西部 western region 日田玖珠 hita kusu 日田市 ひたし hita city 九重町 ここのえまち kokonoe town 玖珠町 くすまち kusu town 竹田市 taketa city たけたし 南部 southern region 佐伯市 saiki city さいきし 豊後大野市 bungoono city ぶんごおおのし bungo ohno city 九州北部地方（山口県を含む） northern kyushu (including yamaguchi)",
  "450000":
    "宮崎県 miyazaki 南部平野部 plain area of southern region 宮崎地区 miyazaki district 宮崎市 みやざきし miyazaki city 国富町 くにとみちょう kunitomi town 綾町 あやちょう aya town 日南・串間地区 nichinan kushima district 日南市 にちなんし nichinan city 串間市 くしまし kushima city 北部平野部 plain area of northern region 延岡・日向地区 nobeoka hyuga district 延岡市 のべおかし nobeoka city 日向市 ひゅうがし hyuga city 門川町 かどがわちょう kadogawa town 西都・高鍋地区 saito takanabe district 西都市 さいとし saito city 高鍋町 たかなべちょう takanabe town 新富町 しんとみちょう shintomi town 木城町 きじょうちょう kijo town 川南町 かわみなみちょう kawaminami town 都農町 つのちょう tsuno town 南部山沿い area along mountains of southern region 小林・えびの地区 kobayashi ebino district 小林市 こばやしし kobayashi city えびの市 えびのし ebino city 高原町 たかはるちょう takaharu town 都城地区 miyakonojo district 都城市 みやこのじょうし miyakonojo city 三股町 みまたちょう mimata town 北部山沿い area along mountains of northern region 高千穂地区 takachiho district 高千穂町 たかちほちょう takachiho town 日之影町 ひのかげちょう hinokage town 五ヶ瀬町 ごかせちょう gokase town 椎葉・美郷地区 shiiba misato district 西米良村 にしめらそん nishimera village 諸塚村 もろつかそん morotsuka village 椎葉村 しいばそん shiiba village 美郷町 みさとちょう misato town 九州南部・奄美地方 southern kyushu and amami",
  "460040":
    "奄美地方 amami region 北部 northern region 奄美市 あまみし amami city 大和村 やまとそん yamato village 宇検村 うけんそん uken village 瀬戸内町 せとうちちょう setouchi town 龍郷町 たつごうちょう tatsugo town 喜界町 きかいちょう kikai town 南部 southern region 徳之島町 とくのしまちょう tokunoshima town 天城町 あまぎちょう amagi town 伊仙町 いせんちょう isen town 和泊町 わどまりちょう wadomari town 知名町 ちなちょう china town 与論町 よろんちょう yoron town 十島村 toshima village としまむら 九州南部・奄美地方 southern kyushu and amami",
  "460100":
    "鹿児島県（奄美地方除く） kagoshima (excluding amami) 薩摩地方 satsuma region 鹿児島・日置 kagoshima hioki 鹿児島市 かごしまし kagoshima city 日置市 ひおきし hioki city いちき串木野市 いちきくしきのし ichikikushikino city 出水・伊佐 izumi isa 阿久根市 あくねし akune city 出水市 いずみし izumi city 伊佐市 いさし isa city 長島町 ながしまちょう nagashima town 川薩・姶良 sensatsu aira 薩摩川内市 さつませんだいし satsumasendai city 霧島市 きりしまし kirishima city 姶良市 あいらし aira city さつま町 さつまちょう satsuma town 湧水町 ゆうすいちょう yusui town 甑島 koshikishima 薩摩川内市甑島 さつませんだいしこしきしま koshikishima, satsumasendai city 指宿・川辺 ibusuki kawanabe 枕崎市 まくらざきし makurazaki city 指宿市 いぶすきし ibusuki city 南さつま市 みなみさつまし minamisatsuma city 南九州市 みなみきゅうしゅうし minamikyushu city 大隅地方 osumi region 曽於 soo 曽於市 そおし soo city 志布志市 しぶしし shibushi city 大崎町 おおさきちょう osaki town 肝属 kimotsuki 鹿屋市 かのやし kanoya city 垂水市 たるみずし tarumizu city 東串良町 ひがしくしらちょう higashikushira town 錦江町 きんこうちょう kinko town 南大隅町 みなみおおすみちょう minamiosumi town 肝付町 きもつきちょう kimotsuki town 種子島・屋久島地方 tanegashima yakushima region 種子島地方 tanegashima region 西之表市 にしのおもてし nishinoomote city 三島村 みしまむら mishima village 中種子町 なかたねちょう nakatane town 南種子町 みなみたねちょう minamitane town 屋久島地方 yakushima region 屋久島町 やくしまちょう yakushima town 九州南部・奄美地方 southern kyushu and amami",
  "471000":
    "沖縄本島地方 okinawa main island 本島中南部 central and southern main island 南部 southern region 那覇市 なはし naha city 浦添市 うらそえし urasoe city 糸満市 いとまんし itoman city 豊見城市 とみぐすくし tomigusuku city 南城市 なんじょうし nanjo city 西原町 にしはらちょう nishihara town 与那原町 よなばるちょう yonabaru town 南風原町 はえばるちょう haebaru town 八重瀬町 やえせちょう yaese town 中部 central region 宜野湾市 ぎのわんし ginowan city 沖縄市 おきなわし okinawa city うるま市 うるまし uruma city 読谷村 よみたんそん yomitan village 嘉手納町 かでなちょう kadena town 北谷町 ちゃたんちょう chatan town 北中城村 きたなかぐすくそん kitanakagusuku village 中城村 なかぐすくそん nakagusuku village 慶良間・粟国諸島 kerama aguni islands 渡嘉敷村 とかしきそん tokashiki village 座間味村 ざまみそん zamami village 粟国村 あぐにそん aguni village 渡名喜村 となきそん tonaki village 本島北部 northern main island 伊是名・伊平屋 izena iheya 伊平屋村 いへやそん iheya village 伊是名村 いぜなそん izena village 国頭地区 kunigami district 国頭村 くにがみそん kunigami village 大宜味村 おおぎみそん ogimi village 東村 ひがしそん higashi village 名護地区 nago district 名護市 なごし nago city 今帰仁村 なきじんそん nakijin village 本部町 もとぶちょう motobu town 伊江村 いえそん ie village 恩納・金武地区 onna kin district 恩納村 おんなそん onna village 宜野座村 ぎのざそん ginoza village 金武町 きんちょう kin town 久米島 kumejima 久米島町 くめじまちょう kumejima town 沖縄地方 okinawa",
  "472000":
    "大東島地方 daitojima region 南大東村 みなみだいとうそん minamidaito village 北大東村 きただいとうそん kitadaito village 沖縄地方 okinawa",
  "473000":
    "宮古島地方 miyakojima region 宮古島 miyakojima 宮古島市 みやこじまし miyakojima city 多良間島 taramajima 多良間村 たらまそん tarama village 沖縄地方 okinawa",
  "474000":
    "八重山地方 yaeyama 石垣島地方 ishigakijima region 石垣市 ishigaki city いしがきし 竹富町 taketomi town たけとみちょう 与那国島地方 yonagunijima region 与那国町 よなぐにちょう yonaguni town 沖縄地方 okinawa",
  "011000":
    "宗谷地方 soya region 宗谷北部 northern soya 稚内市 わっかないし wakkanai city 猿払村 さるふつむら sarufutsu village 豊富町 とよとみちょう toyotomi town 幌延町 ほろのべちょう horonobe town 宗谷南部 southern soya 浜頓別町 はまとんべつちょう hamatombetsu town 中頓別町 なかとんべつちょう nakatombetsu town 枝幸町 えさしちょう esashi town 利尻・礼文 rishiri rebun 礼文町 れぶんちょう rebun town 利尻町 りしりちょう rishiri town 利尻富士町 りしりふじちょう rishirifuji town 北海道地方 hokkaido",
  "012000":
    "上川・留萌地方 kamikawa rumoi 上川地方 kamikawa region 上川北部 northern kamikawa 士別市 しべつし shibetsu city 名寄市 なよろし nayoro city 和寒町 わっさむちょう wassamu town 剣淵町 けんぶちちょう kembuchi town 下川町 しもかわちょう shimokawa town 美深町 びふかちょう bifuka town 音威子府村 おといねっぷむら otoineppu village 中川町 なかがわちょう nakagawa town 幌加内町 ほろかないちょう horokanai town 上川中部 middle kamikawa 旭川市 あさひかわし asahikawa city 鷹栖町 たかすちょう takasu town 東神楽町 ひがしかぐらちょう higashikagura town 当麻町 とうまちょう toma town 比布町 ぴっぷちょう pippu town 愛別町 あいべつちょう aibetsu town 上川町 かみかわちょう kamikawa town 東川町 ひがしかわちょう higashikawa town 美瑛町 びえいちょう biei town 上川南部 southern kamikawa 富良野市 ふらのし furano city 上富良野町 かみふらのちょう kamifurano town 中富良野町 なかふらのちょう nakafurano town 南富良野町 みなみふらのちょう minamifurano town 占冠村 しむかっぷむら shimukappu village 留萌地方 rumoi region 留萌北部 northern rumoi 遠別町 えんべつちょう embetsu town 天塩町 てしおちょう teshio town 留萌中部 middle rumoi 苫前町 とままえちょう tomamae town 羽幌町 はぼろちょう haboro town 羽幌町天売焼尻 はぼろちょうてうりやぎしり teuri yagishiri, haboro town 初山別村 しょさんべつむら shosambetsu village 留萌南部 southern rumoi 留萌市 るもいし rumoi city 増毛町 ましけちょう mashike town 小平町 おびらちょう obira town 北海道地方 hokkaido",
  "013000":
    "網走・北見・紋別地方 abashiri kitami mombetsu 網走地方 abashiri region 網走西部 western abashiri 北見市常呂 きたみしところ tokoro, kitami city 網走市 あばしりし abashiri city 佐呂間町 さろまちょう saroma town 大空町 おおぞらちょう ozora town 網走東部 eastern abashiri 斜里町 しゃりちょう shari town 清里町 きよさとちょう kiyosato town 小清水町 こしみずちょう koshimizu town 網走南部 southern abashiri 美幌町 びほろちょう bihoro town 津別町 つべつちょう tsubetsu town 北見地方 kitami region 北見市北見 きたみしきたみ kitami, kitami city 訓子府町 くんねっぷちょう kunneppu town 置戸町 おけとちょう oketo town 紋別地方 mombetsu region 紋別北部 northern mombetsu 紋別市 もんべつし mombetsu city 滝上町 たきのうえちょう takinoue town 興部町 おこっぺちょう okoppe town 西興部村 にしおこっぺむら nishiokoppe village 雄武町 おうむちょう omu town 紋別南部 southern mombetsu 遠軽町 えんがるちょう engaru town 湧別町 ゆうべつちょう yubetsu town 北海道地方 hokkaido",
  "014030":
    "十勝地方 tokachi region 十勝北部 northern tokachi 上士幌町 かみしほろちょう kamishihoro town 鹿追町 しかおいちょう shikaoi town 新得町 しんとくちょう shintoku town 足寄町 あしょろちょう ashoro town 陸別町 りくべつちょう rikubetsu town 十勝中部 middle tokachi 帯広市 おびひろし obihiro city 音更町 おとふけちょう otofuke town 士幌町 しほろちょう shihoro town 清水町 しみずちょう shimizu town 芽室町 めむろちょう memuro town 幕別町 まくべつちょう makubetsu town 池田町 いけだちょう ikeda town 豊頃町 とよころちょう toyokoro town 本別町 ほんべつちょう hombetsu town 浦幌町 うらほろちょう urahoro town 十勝南部 southern tokachi 中札内村 なかさつないむら nakasatsunai village 更別村 さらべつむら sarabetsu village 大樹町 たいきちょう taiki town 広尾町 ひろおちょう hiroo town 北海道地方 hokkaido",
  "014100":
    "釧路・根室地方 kushiro nemuro 根室地方 nemuro region 根室北部 northern nemuro 中標津町 なかしべつちょう nakashibetsu town 標津町 しべつちょう shibetsu town 羅臼町 らうすちょう rausu town 根室中部 middle central 別海町 べつかいちょう betsukai town 根室南部 southern nemuro 根室市 ねむろし nemuro city 釧路地方 kushiro region 釧路北部 northern kushiro 弟子屈町 てしかがちょう teshikaga town 釧路中部 middle kushiro 釧路市阿寒 くしろしあかん akan, kushiro city 標茶町 しべちゃちょう shibecha town 鶴居村 つるいむら tsurui village 釧路南東部 south-eastern kushiro 厚岸町 あっけしちょう akkeshi town 浜中町 はまなかちょう hamanaka town 釧路南西部 south-western kushiro 釧路市釧路 くしろしくしろ kushiro, kushiro city 釧路市音別 くしろしおんべつ onbetsu, kushiro city 釧路町 くしろちょう kushiro town 白糠町 しらぬかちょう shiranuka town 北海道地方 hokkaido",
  "015000":
    "胆振・日高地方 iburi hidaka 胆振地方 iburi region 胆振西部 western iburi 伊達市伊達 だてしだて date, date city 伊達市大滝 だてしおおたき otaki, date city 豊浦町 とようらちょう toyoura town 壮瞥町 そうべつちょう sobetsu town 洞爺湖町 とうやこちょう toyako town 胆振中部 middle iburi 室蘭市 むろらんし muroran city 苫小牧市 とまこまいし tomakomai city 登別市 のぼりべつし noboribetsu city 白老町 しらおいちょう shiraoi town 胆振東部 eastern iburi 厚真町 あつまちょう atsuma town 安平町 あびらちょう abira town むかわ町 むかわちょう mukawa town 日高地方 hidaka region 日高西部 western hidaka 日高町日高 ひだかちょうひだか hidaka, hidaka town 日高町門別 ひだかちょうもんべつ monbetsu, hidaka town 平取町 びらとりちょう biratori town 日高中部 middle hidaka 新冠町 にいかっぷちょう niikappu town 新ひだか町 しんひだかちょう shinhidaka town 日高東部 eastern hidaka 浦河町 うらかわちょう urakawa town 様似町 さまにちょう samani town えりも町 えりもちょう erimo town 北海道地方 hokkaido",
  "016000":
    "石狩・空知・後志地方 ishikari sorachi shiribeshi 石狩地方 ishikari region 石狩北部 northern ishikari 石狩市 いしかりし ishikari city 当別町 とうべつちょう tobetsu town 新篠津村 しんしのつむら shinshinotsu village 石狩中部 middle ishikari 札幌市 さっぽろし sapporo city 江別市 えべつし ebetsu city 石狩南部 southern ishikari 千歳市 ちとせし chitose city 恵庭市 えにわし eniwa city 北広島市 きたひろしまし kitahiroshima city 空知地方 sorachi region 北空知 northern sorachi 深川市 ふかがわし fukagawa city 妹背牛町 もせうしちょう moseushi town 秩父別町 ちっぷべつちょう chippubetsu town 北竜町 ほくりゅうちょう hokuryu town 沼田町 ぬまたちょう numata town 中空知 middle sorachi 芦別市 あしべつし ashibetsu city 赤平市 あかびらし akabira city 滝川市 たきかわし takikawa city 砂川市 すながわし sunagawa city 歌志内市 うたしないし utashinai city 奈井江町 ないえちょう naie town 上砂川町 かみすながわちょう kamisunagawa town 浦臼町 うらうすちょう urausu town 新十津川町 しんとつかわちょう shintotsukawa town 雨竜町 うりゅうちょう uryu town 南空知 southern sorachi 夕張市 ゆうばりし yubari city 岩見沢市 いわみざわし iwamizawa city 美唄市 びばいし bibai city 三笠市 みかさし mikasa city 南幌町 なんぽろちょう namporo town 由仁町 ゆにちょう yuni town 長沼町 ながぬまちょう naganuma town 栗山町 くりやまちょう kuriyama town 月形町 つきがたちょう tsukigata town 後志地方 shiribeshi region 後志北部 northern shiribeshi 小樽市 おたるし otaru city 積丹町 しゃこたんちょう shakotan town 古平町 ふるびらちょう furubira town 仁木町 にきちょう niki town 余市町 よいちちょう yoichi town 赤井川村 あかいがわむら akaigawa village 羊蹄山麓 the foot of mt. yotei ニセコ町 にせこちょう niseko town 真狩村 まっかりむら makkari village 留寿都村 るすつむら rusutsu village 喜茂別町 きもべつちょう kimobetsu town 京極町 きょうごくちょう kyogoku town 倶知安町 くっちゃんちょう kutchan town 後志西部 western shiribeshi 島牧村 しままきむら shimamaki village 寿都町 すっつちょう suttsu town 黒松内町 くろまつないちょう kuromatsunai town 蘭越町 らんこしちょう rankoshi town 共和町 きょうわちょう kyowa town 岩内町 いわないちょう iwanai town 泊村 とまりむら tomari village 神恵内村 かもえないむら kamoenai village 北海道地方 hokkaido",
  "017000":
    "渡島・檜山地方 oshima hiyama 渡島地方 oshima region 渡島北部 northern oshima 八雲町八雲 やくもちょうやくも yakumo, yakumo town 長万部町 おしゃまんべちょう oshamambe town 渡島東部 eastern oshima 函館市 はこだてし hakodate city 北斗市 ほくとし hokuto city 七飯町 ななえちょう nanae town 鹿部町 しかべちょう shikabe town 森町 もりまち mori town 渡島西部 western oshima 松前町 まつまえちょう matsumae town 福島町 ふくしまちょう fukushima town 知内町 しりうちちょう shiriuchi town 木古内町 きこないちょう kikonai town 檜山地方 hiyama region 檜山北部 northern hiyama 八雲町熊石 やくもちょうくまいし kumaishi, yakumo town 今金町 いまかねちょう imakane town せたな町 せたなちょう setana town 檜山南部 southern hiyama 江差町 えさしちょう esashi town 上ノ国町 かみのくにちょう kaminokuni town 厚沢部町 あっさぶちょう assabu town 乙部町 おとべちょう otobe town 檜山奥尻島 hiyama okushirito 奥尻町 おくしりちょう okushiri town 北海道地方 hokkaido",
  "020000":
    "青森県 aomori 津軽 tsugaru 東青津軽 tosei tsugaru 青森市 あおもりし aomori city 平内町 ひらないまち hiranai town 今別町 いまべつまち imabetsu town 蓬田村 よもぎたむら yomogita village 外ヶ浜町 そとがはままち sotogahama town 北五津軽 kitago tsugaru 五所川原市 ごしょがわらし goshogawara city 板柳町 いたやなぎまち itayanagi town 鶴田町 つるたまち tsuruta town 中泊町 なかどまりまち nakadomari town 西津軽 nishitsugaru つがる市 つがるし tsugaru city 鰺ヶ沢町 あじがさわまち ajigasawa town 深浦町 ふかうらまち fukaura town 中南津軽 chunan tsugaru 弘前市 ひろさきし hirosaki city 黒石市 くろいしし kuroishi city 平川市 ひらかわし hirakawa city 西目屋村 にしめやむら nishimeya village 藤崎町 ふじさきまち fujisaki town 大鰐町 おおわにまち owani town 田舎館村 いなかだてむら inakadate village 下北 shimokita むつ市 むつし mutsu city 大間町 おおままち oma town 東通村 ひがしどおりむら higashidori village 風間浦村 かざまうらむら kazamaura village 佐井村 さいむら sai village 三八上北 sanpachi kamikita 三八 sanpachi 八戸市 はちのへし hachinohe city 三沢市 みさわし misawa city 六戸町 ろくのへまち rokunohe town おいらせ町 おいらせちょう oirase town 三戸町 さんのへまち sannohe town 五戸町 ごのへまち gonohe town 田子町 たっこまち takko town 南部町 なんぶちょう nambu town 階上町 はしかみちょう hashikami town 新郷村 しんごうむら shingo village 上北 kamikita 十和田市 とわだし towada city 野辺地町 のへじまち noheji town 七戸町 しちのへまち shichinohe town 横浜町 よこはままち yokohama town 東北町 とうほくまち tohoku town 六ヶ所村 ろっかしょむら rokkasho village 東北地方 tohoku",
  "030000":
    "岩手県 iwate 内陸 inland 盛岡地域 morioka area 盛岡市 もりおかし morioka city 八幡平市 はちまんたいし hachimantai city 滝沢市 たきざわし takizawa city 雫石町 しずくいしちょう shizukuishi town 葛巻町 くずまきまち kuzumaki town 岩手町 いわてまち iwate town 紫波町 しわちょう shiwa town 矢巾町 やはばちょう yahaba town 二戸地域 ninohe area 二戸市 にのへし ninohe city 軽米町 かるまいまち karumai town 九戸村 くのへむら kunohe village 一戸町 いちのへまち ichinohe town 花北地域 hanakita area 花巻市 はなまきし hanamaki city 北上市 きたかみし kitakami city 西和賀町 にしわがまち nishiwaga town 遠野地域 tono area 遠野市 とおのし tono city 奥州金ケ崎地域 oshu kanegasaki area 奥州市 おうしゅうし oshu city 金ケ崎町 かねがさきちょう kanegasaki town 両磐地域 ryoban area 一関市 いちのせきし ichinoseki city 平泉町 ひらいずみちょう hiraizumi town 沿岸北部 northern coast 久慈地域 kuji area 久慈市 くじし kuji city 普代村 ふだいむら fudai village 野田村 のだむら noda village 洋野町 ひろのちょう hirono town 宮古地域 miyako area 宮古市 みやこし miyako city 山田町 やまだまち yamada town 岩泉町 いわいずみちょう iwaizumi town 田野畑村 たのはたむら tanohata village 沿岸南部 southern coast 釜石地域 kamaishi area 釜石市 かまいしし kamaishi city 大槌町 おおつちちょう otsuchi town 大船渡地域 ofunato area 大船渡市 おおふなとし ofunato city 陸前高田市 りくぜんたかたし rikuzentakata city 住田町 すみたちょう sumita town 東北地方 tohoku",
  "040000":
    "宮城県 miyagi 東部 eastern region 東部仙台 eastern sendai 仙台市東部 せんだいしとうぶ eastern sendai city 塩竈市 しおがまし shiogama city 名取市 なとりし natori city 多賀城市 たがじょうし tagajo city 岩沼市 いわぬまし iwanuma city 富谷市 とみやし tomiya city 亘理町 わたりちょう watari town 山元町 やまもとちょう yamamoto town 松島町 まつしままち matsushima town 七ヶ浜町 しちがはままち shichigahama town 利府町 りふちょう rifu town 大和町東部 たいわちょうとうぶ eastern taiwa town 大郷町 おおさとちょう osato town 石巻地域 ishinomaki area 石巻市 いしのまきし ishinomaki city 東松島市 ひがしまつしまし higashimatsushima city 女川町 おながわちょう onagawa town 東部大崎 eastern osaki 大崎市東部 おおさきしとうぶ eastern osaki city 涌谷町 わくやちょう wakuya town 美里町 みさとまち misato town 気仙沼地域 kesennuma area 気仙沼市 けせんぬまし kesennuma city 南三陸町 みなみさんりくちょう minamisanriku town 東部仙南 eastern sennan 角田市 かくだし kakuda city 大河原町 おおがわらまち ogawara town 村田町 むらたまち murata town 柴田町 しばたまち shibata town 丸森町 まるもりまち marumori town 登米・東部栗原 tome and eastern kurihara 登米市 とめし tome city 栗原市東部 くりはらしとうぶ eastern kurihara city 西部 western region 西部仙台 western sendai 仙台市西部 せんだいしせいぶ western sendai city 大和町西部 たいわちょうせいぶ western taiwa town 大衡村 おおひらむら ohira village 西部仙南 western sennan 白石市 しろいしし shiroishi city 蔵王町 ざおうまち zao town 七ヶ宿町 しちかしゅくまち shichikashuku town 川崎町 かわさきまち kawasaki town 西部大崎 western osaki 大崎市西部 おおさきしせいぶ western osaki city 色麻町 しかまちょう shikama town 加美町 かみまち kami town 西部栗原 western kurihara 栗原市西部 くりはらしせいぶ western kurihara city 東北地方 tohoku",
  "050000":
    "秋田県 akita 沿岸 coast 秋田中央地域 akita central area 秋田市 あきたし akita city 男鹿市 おがし oga city 潟上市 かたがみし katagami city 五城目町 ごじょうめまち gojome town 八郎潟町 はちろうがたまち hachirogata town 井川町 いかわまち ikawa town 大潟村 おおがたむら ogata village 能代山本地域 noshiro yamamoto area 能代市 のしろし noshiro city 藤里町 ふじさとまち fujisato town 三種町 みたねちょう mitane town 八峰町 はっぽうちょう happou town 本荘由利地域 honjo yuri area 由利本荘市 ゆりほんじょうし yurihonjo city にかほ市 にかほし nikaho city 内陸 inland 北秋鹿角地域 hokusyu kazuno area 大館市 おおだてし odate city 鹿角市 かづのし kazuno city 北秋田市 きたあきたし kitaakita city 小坂町 こさかまち kosaka town 上小阿仁村 かみこあにむら kamikoani village 仙北平鹿地域 semboku hiraka area 横手市 よこてし yokote city 大仙市 だいせんし daisen city 仙北市 せんぼくし semboku city 美郷町 みさとちょう misato town 湯沢雄勝地域 yuzawa ogachi area 湯沢市 ゆざわし yuzawa city 羽後町 うごまち ugo town 東成瀬村 ひがしなるせむら higashinaruse village 東北地方 tohoku",
  "060000":
    "山形県 yamagata 村山 murayama 東南村山 south-eastern murayama 山形市 やまがたし yamagata city 上山市 かみのやまし kaminoyama city 天童市 てんどうし tendo city 山辺町 やまのべまち yamanobe town 中山町 なかやままち nakayama town 北村山 northern murayama 村山市 むらやまし murayama city 東根市 ひがしねし higashine city 尾花沢市 おばなざわし obanazawa city 大石田町 おおいしだまち oishida town 西村山 western murayama 寒河江市 さがえし sagae city 河北町 かほくちょう kahoku town 西川町 にしかわまち nishikawa town 朝日町 あさひまち asahi town 大江町 おおえまち oe town 置賜 okitama 東南置賜 south-eastern okitama 米沢市 よねざわし yonezawa city 南陽市 なんようし nanyo city 高畠町 たかはたまち takahata town 川西町 かわにしまち kawanishi town 西置賜 western okitama 長井市 ながいし nagai city 小国町 おぐにまち oguni town 白鷹町 しらたかまち shirataka town 飯豊町 いいでまち iide town 庄内 shonai 庄内北部 northern shonai 酒田市 さかたし sakata city 遊佐町 ゆざまち yuza town 庄内南部 southern shonai 鶴岡市 つるおかし tsuruoka city 三川町 みかわまち mikawa town 庄内町 しょうないまち shonai town 最上 mogami 新庄市 しんじょうし shinjo city 金山町 かねやままち kaneyama town 最上町 もがみまち mogami town 舟形町 ふながたまち funagata town 真室川町 まむろがわまち mamurogawa town 大蔵村 おおくらむら okura village 鮭川村 さけがわむら sakegawa village 戸沢村 とざわむら tozawa village 東北地方 tohoku",
  "070000":
    "福島県 fukushima 中通り nakadori 中通り北部 northern nakadori 福島市 ふくしまし fukushima city 伊達市 だてし date city 桑折町 こおりまち koori town 国見町 くにみまち kunimi town 川俣町 かわまたまち kawamata town 中通り中部 central nakadori 郡山市 こおりやまし koriyama city 須賀川市 すかがわし sukagawa city 二本松市 にほんまつし nihonmatsu city 田村市 たむらし tamura city 本宮市 もとみやし motomiya city 大玉村 おおたまむら otama village 鏡石町 かがみいしまち kagamiishi town 天栄村 てんえいむら tenei village 三春町 みはるまち miharu town 小野町 おのまち ono town 中通り南部 southern nakadori 白河市 しらかわし shirakawa city 西郷村 にしごうむら nishigo village 泉崎村 いずみざきむら izumizaki village 中島村 なかじまむら nakajima village 矢吹町 やぶきまち yabuki town 棚倉町 たなぐらまち tanagura town 矢祭町 やまつりまち yamatsuri town 塙町 はなわまち hanawa town 鮫川村 さめがわむら samegawa village 石川町 いしかわまち ishikawa town 玉川村 たまかわむら tamakawa village 平田村 ひらたむら hirata village 浅川町 あさかわまち asakawa town 古殿町 ふるどのまち furudono town 浜通り hamadori 浜通り北部 northern hamadori 相馬市 そうまし soma city 南相馬市 みなみそうまし minamisoma city 新地町 しんちまち shinchi town 飯舘村 いいたてむら iitate village 浜通り中部 central hamadori 広野町 ひろのまち hirono town 楢葉町 ならはまち naraha town 富岡町 とみおかまち tomioka town 川内村 かわうちむら kawauchi village 大熊町 おおくままち okuma town 双葉町 ふたばまち futaba town 浪江町 なみえまち namie town 葛尾村 かつらおむら katsurao village 浜通り南部 southern hamadori いわき市 いわきし iwaki city 会津 aizu 会津北部 northern aizu 喜多方市 きたかたし kitakata city 北塩原村 きたしおばらむら kitashiobara village 西会津町 にしあいづまち nishiaizu town 磐梯町 ばんだいまち bandai town 猪苗代町 いなわしろまち inawashiro town 会津中部 central aizu 会津若松市 あいづわかまつし aizuwakamatsu city 郡山市湖南 こおりやましこなん konan, koriyama city 会津坂下町 あいづばんげまち aizubange town 湯川村 ゆがわむら yugawa village 柳津町 やないづまち yanaizu town 三島町 みしままち mishima town 金山町 かねやままち kaneyama town 昭和村 しょうわむら showa village 会津美里町 あいづみさとまち aizumisato town 会津南部 southern aizu 天栄村湯本 てんえいむらゆもと yumoto, tenei village 下郷町 しもごうまち shimogo town 檜枝岐村 ひのえまたむら hinoemata village 只見町 ただみまち tadami town 南会津町 みなみあいづまち minamiaizu town 東北地方 tohoku",
  "080000":
    "茨城県 ibaraki 北部 northern region 県央地域 ken-o area 水戸市 みとし mito city 笠間市 かさまし kasama city 小美玉市 おみたまし omitama city 茨城町 いばらきまち ibaraki town 大洗町 おおあらいまち oarai town 城里町 しろさとまち shirosato town 県北地域 kempoku area 日立市 ひたちし hitachi city 常陸太田市 ひたちおおたし hitachiota city 高萩市 たかはぎし takahagi city 北茨城市 きたいばらきし kitaibaraki city ひたちなか市 ひたちなかし hitachinaka city 常陸大宮市 ひたちおおみやし hitachiomiya city 那珂市 なかし naka city 東海村 とうかいむら tokai village 大子町 だいごまち daigo town 南部 southern region 鹿行地域 rokko area 鹿嶋市 かしまし kashima city 潮来市 いたこし itako city 神栖市 かみすし kamisu city 行方市 なめがたし namegata city 鉾田市 ほこたし hokota city 県南地域 kennan area 土浦市 つちうらし tsuchiura city 石岡市 いしおかし ishioka city 龍ケ崎市 りゅうがさきし ryugasaki city 取手市 とりでし toride city 牛久市 うしくし ushiku city つくば市 つくばし tsukuba city 守谷市 もりやし moriya city 稲敷市 いなしきし inashiki city かすみがうら市 かすみがうらし kasumigaura city つくばみらい市 つくばみらいし tsukubamirai city 美浦村 みほむら miho village 阿見町 あみまち ami town 河内町 かわちまち kawachi town 利根町 とねまち tone town 県西地域 kensei area 古河市 こがし koga city 結城市 ゆうきし yuki city 下妻市 しもつまし shimotsuma city 常総市 じょうそうし joso city 筑西市 ちくせいし chikusei city 坂東市 ばんどうし bando city 桜川市 さくらがわし sakuragawa city 八千代町 やちよまち yachiyo town 五霞町 ごかまち goka town 境町 さかいまち sakai town 関東甲信地方 kanto koshin",
  "090000":
    "栃木県 tochigi 南部 southern region 県央部 ken-o part 宇都宮市 うつのみやし utsunomiya city さくら市 さくらし sakura city 上三川町 かみのかわまち kaminokawa town 高根沢町 たかねざわまち takanezawa town 南東部 south-eastern region 真岡市 もおかし moka city 那須烏山市 なすからすやまし nasukarasuyama city 益子町 ましこまち mashiko town 茂木町 もてぎまち motegi town 市貝町 いちかいまち ichikai town 芳賀町 はがまち haga town 那珂川町 なかがわまち nakagawa town 南西部 south-western region 足利市 あしかがし ashikaga city 栃木市 とちぎし tochigi city 佐野市 さのし sano city 鹿沼市 かぬまし kanuma city 小山市 おやまし oyama city 下野市 しもつけし shimotsuke city 壬生町 みぶまち mibu town 野木町 のぎまち nogi town 北部 northern region 那須地域 nasu area 大田原市 おおたわらし ohtawara city 矢板市 やいたし yaita city 那須塩原市 なすしおばらし nasushiobara city 塩谷町 しおやまち shioya town 那須町 なすまち nasu town 日光市 nikko city 日光市今市 にっこうしいまいち imaichi, nikko city 日光市日光 にっこうしにっこう nikko, nikko city 日光市藤原 にっこうしふじわら fujihara, nikko city 日光市足尾 にっこうしあしお ashio, nikko city 日光市栗山 にっこうしくりやま kuriyama, nikko city 関東甲信地方 kanto koshin",
};
